[package]
name = "hashsat"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39 = "2.2.0"
bitcoin = "0.32.6"
clap = { version = "4.5.42", features = ["derive"] }
rand = "0.9.2"
rayon = "1.10.0"
thiserror = "2.0.12"
